"""initial schema

Revision ID: 8eb3ecc4b704
Revises: 
Create Date: 2026-05-28 23:15:12.561919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb3ecc4b704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ruleset', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('world_state', sa.Text(), nullable=False),
    sa.Column('access_code', sa.String(length=12), nullable=False),
    sa.Column('map_data', sa.Text(), nullable=True),
    sa.Column('npcs', sa.Text(), nullable=True),
    sa.Column('quests', sa.Text(), nullable=True),
    sa.Column('party_state', sa.Text(), nullable=True),
    sa.Column('map_annotations', sa.Text(), nullable=True),
    sa.Column('world_time', sa.Text(), nullable=True),
    sa.Column('handouts', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('readalouds', sa.Text(), nullable=True),
    sa.Column('random_tables', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp_current', sa.Integer(), nullable=False),
    sa.Column('hp_max', sa.Integer(), nullable=False),
    sa.Column('stats', sa.Text(), nullable=False),
    sa.Column('inventory', sa.Text(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('spell_slots', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('death_saves', sa.Text(), nullable=True),
    sa.Column('concentration', sa.Text(), nullable=True),
    sa.Column('inspiration', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('spellbook', sa.Text(), nullable=True),
    sa.Column('audit_log', sa.Text(), nullable=True),
    sa.Column('hit_dice_remaining', sa.Integer(), nullable=True),
    sa.Column('exhaustion', sa.Integer(), nullable=True),
    sa.Column('bonds', sa.Text(), nullable=True),
    sa.Column('ideals', sa.Text(), nullable=True),
    sa.Column('flaws', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('tool_proficiencies', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pinned_notes', sa.Text(), nullable=True),
    sa.Column('dm_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('characters')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
